INSERT INTO majors (major_name, major_school) VALUES ("Accountancy", "School of Business");
INSERT INTO majors (major_name, major_school) VALUES ("Anthropology", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("Art History", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("Biology", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("Biophysics", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("Business and Enterprise Management", "School of Business");
INSERT INTO majors (major_name, major_school) VALUES ("Chemistry", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("Chinese Language and Culture", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("Classical Studies", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("Communication", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("Computer Science", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("Economics", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("Education", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("English", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("Finance", "School of Business");
INSERT INTO majors (major_name, major_school) VALUES ("French Studies", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("German", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("German Studies", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("Greek", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("Health and Exercise Science", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("History", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("The Interdisciplinary Major", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("Japanese Language and Culture", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("Latin", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("Mathematical Business", "School of Business");
INSERT INTO majors (major_name, major_school) VALUES ("Mathematical Economics", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("Mathematical Statistics", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("Mathematics", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("Music in Liberal Arts", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("Music Performance", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("Philosophy", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("Physics", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("Political Science", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("Psychology", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("Religious Studies", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("Russian", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("Sociology", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("Spanish", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("Studio Art", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("Theatre", "Liberal Arts College");
INSERT INTO majors (major_name, major_school) VALUES ("Women's, Gender, and Sexuality Studies", "Liberal Arts College");